### ISSUE TITLE
RightClickMenu also work on frontend

### ISSUE THREAD

**Issue by tammoterhark** [olleharstedt/RightClickMenu#1]
At least it disables "normal" right click behaviour on a front end screen.

I wanted to enable FireBug but when RightClickMenu is enabled, you cannot do that with a rightclick.

Please make this very usefull utility only for the admin interface... ;-)

**Comment by olleharstedt** [comment]
Weird, I can't reproduce. Tested in Firefox and Chromium.

**Comment by tammoterhark** [comment]
Are we looking at the same thing: I opened LS with your plugin activated and previewed a (not active) survey. On the preview page, shown in the default template, the right mouse button does not work anymore..

**Comment by olleharstedt** [comment]
Yes, that's exactly what I did. Nevermind, I'll disable the loading of the scripts in front-end anyway, they shouldn't be there.

**Comment by tammoterhark** [comment]
I found out: it was on the develop branche where I was testing. It is OK in 2.5x, but not in 3.0...
Sorry for the confusion.

**Comment by olleharstedt** [comment]
OK. Still, can you update the plugin and try again on 3.0?

**Comment by tammoterhark** [comment]
OK now! Thanks.
