### ISSUE TITLE
Question explorer may become too long

### ISSUE THREAD

**Issue by tammoterhark** [olleharstedt/RightClickMenu#2]
When you have many groups, the question explorer may become too long. You could avoid this by:
* make the question explorer to show only when you click the item
* make the question explorer scrollable (challenging?)

**Comment by tammoterhark** [comment]
![rightclick](https://cloud.githubusercontent.com/assets/6483317/21389167/82f20abe-c780-11e6-939b-ff1f47d8d942.png)

**Comment by tammoterhark** [comment]
And I have a large screen: 1920 x 1200 px

**Comment by olleharstedt** [comment]
That's your question groups?

**Comment by tammoterhark** [comment]
Affirmative

**Comment by tammoterhark** [comment]
Dutch Decent Work Survey: demo.gewoongoedwerkmeter.nl

**Comment by Deusdeorum** [comment]
I was trying to fix that without any result what so ever, same goes when you click to near margins of browser. I was trying a JS-solution where I would identify how close to margins you are and expand the menu to the left instead of right as in the picture, what would be the proper way to 'fix' this? (wide is probably not a problem, just dont click that close to the margins :) )
![right-click-menu](https://cloud.githubusercontent.com/assets/19924558/21390921/8b8d6d9a-c789-11e6-8e3f-c928482b3fb7.png)

**Comment by tammoterhark** [comment]
I would say the easiest would be to show the questions explorer not
expanded in the first place. But secondly (do not know if it is possible)
make the list scrollable.

Also note from my grumpy business partner: using this "thing" copy/paste
with the right mouse button does not seem to work. Would it be an idea to
include that?

=======================
tammo.terhark@gmail.com

Haarlem, The Netherlands
=======================

2016-12-21 14:27 GMT+01:00 hugohonorem <notifications@github.com>:

**Comment by olleharstedt** [comment]
Yeah, I thought about including copy-paste at the top of the menu.

**Comment by olleharstedt** [comment]
But if you open the menu lower down, the page should get bigger, no? Then you can scroll. Not really optimal, but still.

**Comment by tammoterhark** [comment]
Guess my number of groups is too high... But this may occur more often.

![afbeelding](https://cloud.githubusercontent.com/assets/6483317/21391181/c7abf67e-c78a-11e6-9a87-534578b93340.png)

**Comment by tammoterhark** [comment]
When the length of the right hand menu is larger than the page you are in trouble. No matter where you start...

**Comment by olleharstedt** [comment]
Could you mail that survey to me?

**Comment by tammoterhark** [comment]
Please send me your mail. I do not want this to go public.

**Comment by olleharstedt** [comment]
> If you are using visible for either overflow-x or overflow-y and something other than visible for the other. The visible value is interpreted as auto.

Well, there goes my easy fix... http://stackoverflow.com/questions/6421966/css-overflow-x-visible-and-overflow-y-hidden-causing-scrollbar-issue

**Comment by tammoterhark** [comment]
Does this need to be fixed in your plugin or in the A-UI of LS?

**Comment by tammoterhark** [comment]
And: if it is possible to scroll: please let the cursor start at the top: close to copy/paste and the other menu items....

**Comment by tammoterhark** [comment]
Any news? Would it be possible to include copy/cut/paste?

**Comment by olleharstedt** [comment]
The "too many groups" problem has to fixed in my plugin.

Copy/cut/paste - will have a look tonight.

**Comment by olleharstedt** [comment]
OK, I've added menu items for copy/paste/cut. I only got copy to work on Firefox and Chrome, so... the support is not so wide for these features.

**Comment by olleharstedt** [comment]
Maybe I can just add some "pagination" to the group list. If there are too many groups, it will create an extra submenu like

    Groups (1/2)
    Groups (2/2)

and so on.

**Comment by tammoterhark** [comment]
Yes let's try. Is an extra column (scrollable) possible?

**Comment by olleharstedt** [comment]
Did not get scrolling to work inside the submenu. CSS is a bitch. That's why I want to try the other alternative.

**Comment by tammoterhark** [comment]
OK, think of the Pareto rule: with how many groups can you cover 80% (or more) of all surveys?

**Comment by tammoterhark** [comment]
And what is the minimum screen height this should fit on?

**Comment by tammoterhark** [comment]
Could this help?
http://stackoverflow.com/questions/5209545/css-overflow-yvisible-overflow-xscroll

**Comment by olleharstedt** [comment]
Maybe. But I'm working within the context of Bootstrap. You never know.

**Comment by olleharstedt** [comment]
OK, I've implemented the solution splitting question groups into chunks. Please pull and test.

**Comment by tammoterhark** [comment]
This works very well now. Thank you!
