### ISSUE TITLE
Error when right clicking on survey overview

### ISSUE THREAD

**Issue by tammoterhark** [olleharstedt/RightClickMenu#3]
Notice: Undefined variable: groupChunks in D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\plugins\RightClickMenu\views\menu.php on line 181

**Comment by olleharstedt** [comment]
I thought I fixed that. Can you pull again, please?

**Comment by tammoterhark** [comment]
Yes, works.
