### ISSUE TITLE
Error when clicking on survey

### ISSUE THREAD

**Issue by tammoterhark** [olleharstedt/RightClickMenu#4]
Notice: Undefined variable: plugin in D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\plugins\RightClickMenu\views\menu.php on line 205

Fatal error: Call to a member function renderPartial() on a non-object in D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\plugins\RightClickMenu\views\menu.php on line 205

**Comment by tammoterhark** [comment]
Stack trace:

#0 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\framework\web\CBaseController.php(126): require("D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com...")
#1 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\framework\web\CBaseController.php(95): CBaseController->renderInternal("D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com...", array("questionGroups" => array()), true)
#2 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\framework\web\CController.php(869): CBaseController->renderFile("D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com...", array("questionGroups" => array()), true)
#3 	
–
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\application\libraries\PluginManager\PluginBase.php(266): CController->renderPartial("plugin_views_folder11.views.menu", array("questionGroups" => array()), true, false)

261      */
262     public function renderPartial($viewfile, $data, $return = false, $processOutput = false)
263     {
264         $alias = 'plugin_views_folder' . $this->id;
265         \Yii::setPathOfAlias($alias, $this->getDir());
266         return \Yii::app()->controller->renderPartial($alias .'.views.' . $viewfile, $data, $return, $processOutput);
267     }
268 
269     /**
270      * To find the plugin locale file, we need late runtime result of __DIR__.
271      * Solution copied from http://stackoverflow.com/questions/18100689/php-dir-evaluated-runtime-late-binding

#4 	
–
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\plugins\RightClickMenu\RightClickMenu.php(56): ls\pluginmanager\PluginBase->renderPartial("menu", array("questionGroups" => array()), true)

51         $data = $event->get('data');
52 
53         // No survey id = no question explorer
54         if (!isset($data['surveyid'])) {
55             $data = array('questionGroups' => array());
56             $content = $this->renderPartial('menu', $data, true);
57             echo $content;
58             return;
59         }
60 
61         $surveyId = $data['surveyid'];

#5 	
 unknown(0): RightClickMenu->beforeAdminMenuRender()
#6 	
–
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\application\libraries\PluginManager\PluginManager.php(192): call_user_func(array(RightClickMenu, "beforeAdminMenuRender"))

187                 {
188                     if (!$event->isStopped()
189                      && (empty($target) || in_array(get_class($subscription[0]), $target)))
190                     {
191                         $subscription[0]->setEvent($event);
192                         call_user_func($subscription);
193                     }
194                 }
195             }
196 
197             return $event;

#7 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\application\core\Survey_Common_Action.php(1461): ls\pluginmanager\PluginManager->dispatchEvent(PluginEvent)
#8 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\application\core\Survey_Common_Action.php(537): Survey_Common_Action->fetchExtraMenus(array("issuperadmin" => true, "showLastSurvey" => true, "surveyTitle" => "Sample LimeSurvey EN/FR/DE(ID:282267)", "surveyUrl" => "/index.php/admin/survey/sa/view/surveyid/282267", ...))
#9 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\application\core\Survey_Common_Action.php(247): Survey_Common_Action->_showadminmenu(array("issuperadmin" => true, "showLastSurvey" => true, "surveyTitle" => "Sample LimeSurvey EN/FR/DE(ID:282267)", "surveyUrl" => "/index.php/admin/survey/sa/view/surveyid/282267", ...))
#10 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\application\controllers\admin\index.php(93): Survey_Common_Action->_renderWrappedTemplate("super", "welcome", array("issuperadmin" => true, "showLastSurvey" => true, "surveyTitle" => "Sample LimeSurvey EN/FR/DE(ID:282267)", "surveyUrl" => "/index.php/admin/survey/sa/view/surveyid/282267", ...))
#11 	
 unknown(0): Index->run()
#12 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Index, array())
#13 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\application\core\Survey_Common_Action.php(101): CAction->runWithParamsInternal(Index, ReflectionMethod, array())
#14 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\framework\web\CController.php(308): Survey_Common_Action->runWithParams(array())
#15 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\framework\web\CController.php(286): CController->runAction(Index)
#16 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\framework\web\CController.php(265): CController->runActionWithFilters(Index, array())
#17 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\application\controllers\AdminController.php(177): CController->run("")
#18 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\framework\web\CWebApplication.php(282): AdminController->run("")
#19 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\framework\web\CWebApplication.php(141): CWebApplication->runController("admin")
#20 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 	
+
 D:\Dropbox\sites\drupal\hoofdtoegang\survey.toolsforresearch.com\public_html\index.php(214): CApplication->run()

**Comment by tammoterhark** [comment]
I love the fact that you do this on your free day. But you are not there yet, I'm sorry to say...

**Comment by olleharstedt** [comment]
Oh, this is silly of me! I added a feature in LS to be able to handle views better from plugin. You would have to wait for the next release to use it. >< Hm.

**Comment by olleharstedt** [comment]
Either that or do a pull of LS master.

**Comment by olleharstedt** [comment]
OK, I updated the plugin to require at least version 2.62.3. That will be the next version of LS (or 2.63.0).

**Comment by tammoterhark** [comment]
Yes, works on Git version.
